package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategorylinksId generated by hbm2java
 */
@Embeddable
public class CategorylinksId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6761943863804031379L;
	private int clFrom;
	private String clTo;
	private byte[] clSortkey;
	private String clSortkeyPrefix;
	private Date clTimestamp;
	private byte[] clCollation;
	private String clType;

	public CategorylinksId() {
	}

	public CategorylinksId(int clFrom, String clTo, byte[] clSortkey, String clSortkeyPrefix, Date clTimestamp,
			byte[] clCollation, String clType) {
		this.clFrom = clFrom;
		this.clTo = clTo;
		this.clSortkey = clSortkey;
		this.clSortkeyPrefix = clSortkeyPrefix;
		this.clTimestamp = clTimestamp;
		this.clCollation = clCollation;
		this.clType = clType;
	}

	@Column(name = "cl_from", nullable = false)
	public int getClFrom() {
		return this.clFrom;
	}

	public void setClFrom(int clFrom) {
		this.clFrom = clFrom;
	}

	@Column(name = "cl_to", nullable = false)
	public String getClTo() {
		return this.clTo;
	}

	public void setClTo(String clTo) {
		this.clTo = clTo;
	}

	@Column(name = "cl_sortkey", nullable = false)
	public byte[] getClSortkey() {
		return this.clSortkey;
	}

	public void setClSortkey(byte[] clSortkey) {
		this.clSortkey = clSortkey;
	}

	@Column(name = "cl_sortkey_prefix", nullable = false)
	public String getClSortkeyPrefix() {
		return this.clSortkeyPrefix;
	}

	public void setClSortkeyPrefix(String clSortkeyPrefix) {
		this.clSortkeyPrefix = clSortkeyPrefix;
	}

	@Column(name = "cl_timestamp", nullable = false, length = 19)
	public Date getClTimestamp() {
		return this.clTimestamp;
	}

	public void setClTimestamp(Date clTimestamp) {
		this.clTimestamp = clTimestamp;
	}

	@Column(name = "cl_collation", nullable = false)
	public byte[] getClCollation() {
		return this.clCollation;
	}

	public void setClCollation(byte[] clCollation) {
		this.clCollation = clCollation;
	}

	@Column(name = "cl_type", nullable = false, length = 6)
	public String getClType() {
		return this.clType;
	}

	public void setClType(String clType) {
		this.clType = clType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategorylinksId))
			return false;
		CategorylinksId castOther = (CategorylinksId) other;

		return (this.getClFrom() == castOther.getClFrom())
				&& ((this.getClTo() == castOther.getClTo()) || (this.getClTo() != null && castOther.getClTo() != null
						&& this.getClTo().equals(castOther.getClTo())))
				&& ((this.getClSortkey() == castOther.getClSortkey())
						|| (this.getClSortkey() != null && castOther.getClSortkey() != null
								&& Arrays.equals(this.getClSortkey(), castOther.getClSortkey())))
				&& ((this.getClSortkeyPrefix() == castOther.getClSortkeyPrefix())
						|| (this.getClSortkeyPrefix() != null && castOther.getClSortkeyPrefix() != null
								&& this.getClSortkeyPrefix().equals(castOther.getClSortkeyPrefix())))
				&& ((this.getClTimestamp() == castOther.getClTimestamp())
						|| (this.getClTimestamp() != null && castOther.getClTimestamp() != null
								&& this.getClTimestamp().equals(castOther.getClTimestamp())))
				&& ((this.getClCollation() == castOther.getClCollation())
						|| (this.getClCollation() != null && castOther.getClCollation() != null
								&& Arrays.equals(this.getClCollation(), castOther.getClCollation())))
				&& ((this.getClType() == castOther.getClType()) || (this.getClType() != null
						&& castOther.getClType() != null && this.getClType().equals(castOther.getClType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClFrom();
		result = 37 * result + (getClTo() == null ? 0 : this.getClTo().hashCode());
		int clSortkeyHashcode = 0;
		byte[] clSortkeyProperty = this.getClSortkey();
		if (clSortkeyProperty != null) {
			clSortkeyHashcode = 1;
			for (int i = 0; i < clSortkeyProperty.length; i++) {
				clSortkeyHashcode = 37 * clSortkeyHashcode + clSortkeyProperty[i];
			}
		}

		result = 37 * result + clSortkeyHashcode;

		result = 37 * result + (getClSortkeyPrefix() == null ? 0 : this.getClSortkeyPrefix().hashCode());
		result = 37 * result + (getClTimestamp() == null ? 0 : this.getClTimestamp().hashCode());
		int clCollationHashcode = 0;
		byte[] clCollationProperty = this.getClCollation();
		if (clCollationProperty != null) {
			clCollationHashcode = 1;
			for (int i = 0; i < clCollationProperty.length; i++) {
				clCollationHashcode = 37 * clCollationHashcode + clCollationProperty[i];
			}
		}

		result = 37 * result + clCollationHashcode;

		result = 37 * result + (getClType() == null ? 0 : this.getClType().hashCode());
		return result;
	}

}
