package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categorylinks generated by hbm2java
 */
@Entity
@Table(name = "categorylinks", catalog = "mediawiki", uniqueConstraints = @UniqueConstraint(columnNames = { "cl_from",
		"cl_to" }))
public class Categorylinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 671167056420197936L;
	private CategorylinksId id;

	public Categorylinks() {
	}

	public Categorylinks(CategorylinksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "clFrom", column = @Column(name = "cl_from", nullable = false)),
			@AttributeOverride(name = "clTo", column = @Column(name = "cl_to", nullable = false)),
			@AttributeOverride(name = "clSortkey", column = @Column(name = "cl_sortkey", nullable = false)),
			@AttributeOverride(name = "clSortkeyPrefix", column = @Column(name = "cl_sortkey_prefix", nullable = false)),
			@AttributeOverride(name = "clTimestamp", column = @Column(name = "cl_timestamp", nullable = false, length = 19)),
			@AttributeOverride(name = "clCollation", column = @Column(name = "cl_collation", nullable = false)),
			@AttributeOverride(name = "clType", column = @Column(name = "cl_type", nullable = false, length = 6)) })
	public CategorylinksId getId() {
		return this.id;
	}

	public void setId(CategorylinksId id) {
		this.id = id;
	}

}
