package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Externallinks generated by hbm2java
 */
@Entity
@Table(name = "externallinks", catalog = "mediawiki")
public class Externallinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5502982883661272791L;
	private Integer elId;
	private int elFrom;
	private byte[] elTo;
	private byte[] elIndex;
	private byte[] elIndex60;

	public Externallinks() {
	}

	public Externallinks(int elFrom, byte[] elTo, byte[] elIndex, byte[] elIndex60) {
		this.elFrom = elFrom;
		this.elTo = elTo;
		this.elIndex = elIndex;
		this.elIndex60 = elIndex60;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "el_id", unique = true, nullable = false)
	public Integer getElId() {
		return this.elId;
	}

	public void setElId(Integer elId) {
		this.elId = elId;
	}

	@Column(name = "el_from", nullable = false)
	public int getElFrom() {
		return this.elFrom;
	}

	public void setElFrom(int elFrom) {
		this.elFrom = elFrom;
	}

	@Column(name = "el_to", nullable = false)
	public byte[] getElTo() {
		return this.elTo;
	}

	public void setElTo(byte[] elTo) {
		this.elTo = elTo;
	}

	@Column(name = "el_index", nullable = false)
	public byte[] getElIndex() {
		return this.elIndex;
	}

	public void setElIndex(byte[] elIndex) {
		this.elIndex = elIndex;
	}

	@Column(name = "el_index_60", nullable = false)
	public byte[] getElIndex60() {
		return this.elIndex60;
	}

	public void setElIndex60(byte[] elIndex60) {
		this.elIndex60 = elIndex60;
	}

}
