package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Iwlinks generated by hbm2java
 */
@Entity
@Table(name = "iwlinks", catalog = "mediawiki", uniqueConstraints = @UniqueConstraint(columnNames = { "iwl_from",
		"iwl_prefix", "iwl_title" }))
public class Iwlinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8613399840936521450L;
	private IwlinksId id;

	public Iwlinks() {
	}

	public Iwlinks(IwlinksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "iwlFrom", column = @Column(name = "iwl_from", nullable = false)),
			@AttributeOverride(name = "iwlPrefix", column = @Column(name = "iwl_prefix", nullable = false)),
			@AttributeOverride(name = "iwlTitle", column = @Column(name = "iwl_title", nullable = false)) })
	public IwlinksId getId() {
		return this.id;
	}

	public void setId(IwlinksId id) {
		this.id = id;
	}

}
