package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pagelinks generated by hbm2java
 */
@Entity
@Table(name = "pagelinks", catalog = "mediawiki", uniqueConstraints = @UniqueConstraint(columnNames = { "pl_from",
		"pl_namespace", "pl_title" }))
public class Pagelinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1239313692016254136L;
	private PagelinksId id;

	public Pagelinks() {
	}

	public Pagelinks(PagelinksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "plFrom", column = @Column(name = "pl_from", nullable = false)),
			@AttributeOverride(name = "plFromNamespace", column = @Column(name = "pl_from_namespace", nullable = false)),
			@AttributeOverride(name = "plNamespace", column = @Column(name = "pl_namespace", nullable = false)),
			@AttributeOverride(name = "plTitle", column = @Column(name = "pl_title", nullable = false)) })
	public PagelinksId getId() {
		return this.id;
	}

	public void setId(PagelinksId id) {
		this.id = id;
	}

}
