package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagelinksId generated by hbm2java
 */
@Embeddable
public class PagelinksId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6368547838320084250L;
	private int plFrom;
	private int plFromNamespace;
	private int plNamespace;
	private String plTitle;

	public PagelinksId() {
	}

	public PagelinksId(int plFrom, int plFromNamespace, int plNamespace, String plTitle) {
		this.plFrom = plFrom;
		this.plFromNamespace = plFromNamespace;
		this.plNamespace = plNamespace;
		this.plTitle = plTitle;
	}

	@Column(name = "pl_from", nullable = false)
	public int getPlFrom() {
		return this.plFrom;
	}

	public void setPlFrom(int plFrom) {
		this.plFrom = plFrom;
	}

	@Column(name = "pl_from_namespace", nullable = false)
	public int getPlFromNamespace() {
		return this.plFromNamespace;
	}

	public void setPlFromNamespace(int plFromNamespace) {
		this.plFromNamespace = plFromNamespace;
	}

	@Column(name = "pl_namespace", nullable = false)
	public int getPlNamespace() {
		return this.plNamespace;
	}

	public void setPlNamespace(int plNamespace) {
		this.plNamespace = plNamespace;
	}

	@Column(name = "pl_title", nullable = false)
	public String getPlTitle() {
		return this.plTitle;
	}

	public void setPlTitle(String plTitle) {
		this.plTitle = plTitle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagelinksId))
			return false;
		PagelinksId castOther = (PagelinksId) other;

		return (this.getPlFrom() == castOther.getPlFrom())
				&& (this.getPlFromNamespace() == castOther.getPlFromNamespace())
				&& (this.getPlNamespace() == castOther.getPlNamespace())
				&& ((this.getPlTitle() == castOther.getPlTitle()) || (this.getPlTitle() != null
						&& castOther.getPlTitle() != null && this.getPlTitle().equals(castOther.getPlTitle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlFrom();
		result = 37 * result + this.getPlFromNamespace();
		result = 37 * result + this.getPlNamespace();
		result = 37 * result + (getPlTitle() == null ? 0 : this.getPlTitle().hashCode());
		return result;
	}

}
