package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProtectedTitles generated by hbm2java
 */
@Entity
@Table(name = "protected_titles", catalog = "mediawiki", uniqueConstraints = @UniqueConstraint(columnNames = {
		"pt_namespace", "pt_title" }))
public class ProtectedTitles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9213373222780878588L;
	private ProtectedTitlesId id;

	public ProtectedTitles() {
	}

	public ProtectedTitles(ProtectedTitlesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ptNamespace", column = @Column(name = "pt_namespace", nullable = false)),
			@AttributeOverride(name = "ptTitle", column = @Column(name = "pt_title", nullable = false)),
			@AttributeOverride(name = "ptUser", column = @Column(name = "pt_user", nullable = false)),
			@AttributeOverride(name = "ptReason", column = @Column(name = "pt_reason")),
			@AttributeOverride(name = "ptTimestamp", column = @Column(name = "pt_timestamp", nullable = false)),
			@AttributeOverride(name = "ptExpiry", column = @Column(name = "pt_expiry", nullable = false)),
			@AttributeOverride(name = "ptCreatePerm", column = @Column(name = "pt_create_perm", nullable = false)) })
	public ProtectedTitlesId getId() {
		return this.id;
	}

	public void setId(ProtectedTitlesId id) {
		this.id = id;
	}

}
