package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Redirect generated by hbm2java
 */
@Entity
@Table(name = "redirect", catalog = "mediawiki")
public class Redirect implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9208632941505411200L;
	private int rdFrom;
	private int rdNamespace;
	private String rdTitle;
	private String rdInterwiki;
	private String rdFragment;

	public Redirect() {
	}

	public Redirect(int rdFrom, int rdNamespace, String rdTitle) {
		this.rdFrom = rdFrom;
		this.rdNamespace = rdNamespace;
		this.rdTitle = rdTitle;
	}

	public Redirect(int rdFrom, int rdNamespace, String rdTitle, String rdInterwiki, String rdFragment) {
		this.rdFrom = rdFrom;
		this.rdNamespace = rdNamespace;
		this.rdTitle = rdTitle;
		this.rdInterwiki = rdInterwiki;
		this.rdFragment = rdFragment;
	}

	@Id

	@Column(name = "rd_from", unique = true, nullable = false)
	public int getRdFrom() {
		return this.rdFrom;
	}

	public void setRdFrom(int rdFrom) {
		this.rdFrom = rdFrom;
	}

	@Column(name = "rd_namespace", nullable = false)
	public int getRdNamespace() {
		return this.rdNamespace;
	}

	public void setRdNamespace(int rdNamespace) {
		this.rdNamespace = rdNamespace;
	}

	@Column(name = "rd_title", nullable = false)
	public String getRdTitle() {
		return this.rdTitle;
	}

	public void setRdTitle(String rdTitle) {
		this.rdTitle = rdTitle;
	}

	@Column(name = "rd_interwiki", length = 32)
	public String getRdInterwiki() {
		return this.rdInterwiki;
	}

	public void setRdInterwiki(String rdInterwiki) {
		this.rdInterwiki = rdInterwiki;
	}

	@Column(name = "rd_fragment")
	public String getRdFragment() {
		return this.rdFragment;
	}

	public void setRdFragment(String rdFragment) {
		this.rdFragment = rdFragment;
	}

}
