package de.rwth.i9.cimt.model.wikipedia;
// Generated Mar 14, 2017 3:48:09 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Text generated by hbm2java
 */
@Entity
@Table(name = "text", catalog = "mediawiki")
public class Text implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8079277892495312412L;
	private Integer oldId;
	private byte[] oldText;
	private byte[] oldFlags;

	public Text() {
	}

	public Text(byte[] oldText, byte[] oldFlags) {
		this.oldText = oldText;
		this.oldFlags = oldFlags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "old_id", unique = true, nullable = false)
	public Integer getOldId() {
		return this.oldId;
	}

	public void setOldId(Integer oldId) {
		this.oldId = oldId;
	}

	@Column(name = "old_text", nullable = false)
	public byte[] getOldText() {
		return this.oldText;
	}

	public void setOldText(byte[] oldText) {
		this.oldText = oldText;
	}

	@Column(name = "old_flags", nullable = false)
	public byte[] getOldFlags() {
		return this.oldFlags;
	}

	public void setOldFlags(byte[] oldFlags) {
		this.oldFlags = oldFlags;
	}

}
